services:
  web:
    build: .
    ports:
      - "4000:4000"
      - "35729:35729"  # LiveReload port
    volumes:
      - .:/app
      - ruby_3_4_bundle_cache:/usr/local/bundle
    working_dir: /app
    environment:
      - BUNDLE_PATH=/usr/local/bundle
      - JEKYLL_ENV=development
    command: bash -c "bundle install && bundle exec jekyll serve --host 0.0.0.0 --watch --force_polling --incremental"

volumes:
  ruby_3_4_bundle_cache:
